### ISSUE TITLE
sample call?

### ISSUE THREAD

**Issue by ngalbraith** [ooi-data-review/ooi-realtime-plotting#1]
Great to have this example, thanks!

I'm having trouble customizing it to get multiple variables (or anything) from the METBK. Is there an example that just makes the call to the server, i.e. 
d=requests.get(request_url, params=params, auth=auth)
without plotting, waiting, etc? I'm planning to get multiple variables, and to make the
request intermittently so I don't think I need ThreadPoolExecutor, but should be able to
do the requests.get and capture the output.

All I'm getting is a <Response [500]> - I suspect my request has some errors, unspecified.

Is params['user'] meant to be blank, or should I put my 'normal' portal user name there?
Thanks again - Nan Galbraith

**Comment by friedrichknuth** [comment]
Hi Nan,

Have a look at the demos in https://github.com/ooi-data-review/m2m_demo and let me know if that helps answer your questions. See the Synchronous Request by Parameter example in the botpt_m2m.ipynb script.

Also, have a look at this website as a reference http://ooi.visualocean.net/instruments/view/CE02SHSM-SBD11-06-METBKA000#streams

To find the parameter numbers (PD numbers) you can go to the METBK you are looking for and click on the parameters under a given stream.

Hope this helps! Any further questions, feel free to submit an issue or send an email to help@oceanobservatories.org.

**Comment by friedrichknuth** [comment]
I think the issue you ran into is that request_current_data.py requests the last 10 seconds of data from present and then whatever is new from there. This is fine for Cabled data streaming in at a fast rate <1 sec, but METBK is likely sampling and telemetering data at a far slower rate. If there is no data in the time frame being requested, you will get a 500 error. The m2m demo linked above should give you the building blocks to set up a routine customized for METBK data density. Please email if you have further questions!
